-- 3.2 DDL
--CREATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP
--(
--	SUBWAY_STATN_NO CHAR(6) NOT NULL,
--	STD_YM CHAR(6) NOT NULL,
--	BEGIN_TIME CHAR(4) NOT NULL,
--	END_TIME CHAR(4) NOT NULL,
--	TK_GFF_SE_CD VARCHAR2(6) NOT NULL,
--	TK_GFF_CNT NUMBER(15) NOT NULL,
--	CONSTRAINT PK_TB_SUBWAY_STATN_TK_GFF_TMP PRIMARY KEY
--		(SUBWAY_STATN_NO, STD_YM, BEGIN_TIME, END_TIME, TK_GFF_SE_CD)	
--);

--ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP 
--ADD CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1
--FOREIGN KEY (SUBWAY_STATN_NO) REFERENCES TB_SUBWAY_STATN_TMP (SUBWAY_STATN_NO);

-- 3.2.6 ALTER TABLE

ALTER TABLE TB_SUBWAY_STATN_TMP ADD (OPEN_YN CHAR(1)); 
COMMENT ON COLUMN SQLD.TB_SUBWAY_STATN_TMP.OPEN_YN IS '운영여부';

--ALTER TABLE TB_SUBWAY_STATN_TMP DROP COLUMN OPEN_YN;

ALTER TABLE TB_SUBWAY_STATN_TMP MODIFY (
	OPEN_YN NUMBER(1)
	DEFAULT 0 NOT NULL
	NOVALIDATE );

ALTER TABLE TB_SUBWAY_STATN_TMP
	RENAME COLUMN OPEN_YN TO OPERATION_YN;

ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP 
	DROP CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1;

ALTER TABLE TB_SUBWAY_STATN_TK_GFF_TMP 
ADD CONSTRAINT FK_TB_SUBWAY_STATN_TK_GFF_TMP1
FOREIGN KEY ( SUBWAY_STATN_NO )
REFERENCES TB_SUBWAY_STATN_TMP (SUBWAY_STATN_NO);

RENAME TB_SUBWAY_STATN_TK_GFF_TMP TO TB_SUBWAY_STATN_TK_GFF_TMP_2;

TRUNCATE TABLE TB_SUBWAY_STATN_TK_GFF_TMP_2;

DROP TABLE TB_SUBWAY_STATN_TK_GFF_TMP_2;
DROP TABLE TB_SUBWAY_STATN_TMP;
DROP TABLE TB_RN_TMP;