DROP TABLE DEPT;

CREATE TABLE DEPT (
	DEPTNO VARCHAR2(4) PRIMARY KEY,
	DEPTNAME VARCHAR2(20)
);

SELECT * FROM DEPT;

INSERT INTO DEPT VALUES('1000', '인사팀');
INSERT INTO DEPT VALUES('1001', '총무팀');
INSERT INTO DEPT(DEPTNO) VALUES ('1002');
INSERT INTO DEPT(DEPTNO, DEPTNAME) VALUES('1003', '영업팀');
INSERT INTO DEPT VALUES('1004');

DROP TABLE EMP;

CREATE TABLE EMP
(
	EMPNO NUMBER(10)
	, ENAME VARCHAR2(20)
	, SAL NUMBER(10, 2) DEFAULT 0
	, DEPTNO VARCHAR2(4) NOT NULL
	, CREATEDATE DATE DEFAULT SYSDATE
	, CONSTRAINT E_PK PRIMARY KEY (EMPNO)
	, CONSTRAINT D_FK FOREIGN KEY (DEPTNO) REFERENCES DEPT(DEPTNO)
		ON DELETE CASCADE
);


INSERT INTO EMP VALUES(100, '가나다', 1000, '1000', DEFAULT); -- DEFAULT 값이 있는 컬럼은 DEFAULT문을 써주면 들어간다.
INSERT INTO EMP VALUES(101, '와우산장', 1001, '1001', NULL); -- NULL을 써주어도 DEFAULT값이 들어가지 않는다.
INSERT INTO EMP(EMPNO, ENAME, SAL, DEPTNO) VALUES(102, 'SQLD', 1002, '1002'); -- DEFAULT 값이 있는 컬럼을 빼고 나머지를 명시하고 넣어주면 자동으로 들어간다
INSERT INTO EMP DEFAULT VALUES;
INSERT INTO EMP VALUES(103, '우왁ㅋ', 5000, '1004', DEFAULT);

SELECT * FROM EMP;
SELECT * FROM DEPT;
DELETE FROM DEPT WHERE DEPTNO='1000'; -- ON DELETE CASCADE에 의해 EMP의 참조되는 행이 삭제됨

ALTER TABLE DEPT RENAME TO NEW_DEPT;
ALTER TABLE NEW_DEPT RENAME TO DEPT_AAA;
ALTER TABLE DEPT_AAA RENAME TO DEPT;
ALTER TABLE DEPT RENAME COLUMN DEPTNO TO DEPTNO_NEW;

SELECT * FROM DEPT_AAA;

ALTER TABLE EMP ADD(
	AGE NUMBER(3)
);
ALTER TABLE EMP DROP COLUMN AGE;
ALTER TABLE EMP MODIFY (AGE NUMBER(4) NOT NULL);

CREATE TABLE BONUS
	( ENAME VARCHAR2(10)
	, JOB	VARCHAR2(9)
	, SAL	NUMBER
	, COMM	NUMBER	
	);

INSERT INTO BONUS VALUES('가', '나', 100, 1000);
INSERT INTO BONUS VALUES('다', '라', 100, 2000);
INSERT INTO BONUS VALUES('마', '바', 110, 1000);

SELECT * FROM BONUS;

TRUNCATE TABLE BONUS;
ALTER TABLE TRUNCATE COLUMN COMM;   --??
UPDATE BONUS SET JOB=NULL;  		-- 컬럼만 날리려면 이렇게
UPDATE BONUS SET JOB='라' WHERE SAL=100;
UPDATE BONUS SET JOB='고' WHERE COMM=1000;
UPDATE BONUS SET JOB='바' WHERE SAL=110;
UPDATE BONUS SET JOB='나' WHERE SAL=100 AND COMM=1000;

DELETE FROM BONUS WHERE JOB='나'; -- ROW가 날라간다. 컬럼 지정하지 않으면

SELECT ENAME, SAL, SAL+10, SAL*2, SAL/2 FROM BONUS;
SELECT ENAME, '급여 ' || SAL || '원' FROM BONUS;
SELECT ENAME, '￦' || TO_CHAR(SAL, '9,999,999.99') FROM BONUS;

SELECT * FROM BONUS ORDER BY COMM;
