

SELECT DEPTNO, JOB FROM EMP;

SELECT DISTINCT DEPTNO, JOB FROM EMP;

SELECT DISTINCT JOB, DEPTNO FROM EMP;

SELECT DECODE(2, NULL, 'TRUE', 'FALSE') FROM DUAL;
SELECT DECODE(NULL, NULL, 'TRUE', 'FALSE') FROM DUAL;

SELECT * FROM TAB_A;
SELECT * FROM TAB_A WHERE COL1 != COL2;

select * from tab1;
UPDATE TAB1 SET C2 = '' WHERE C1='a';
COMMIT;
SELECT C2 FROM TAB1 WHERE C1='b';
SELECT NVL(C2, 'X') FROM TAB1 WHERE C1 = 'a';
SELECT COUNT(C1) FROM TAB1 WHERE C2= NULL;
SELECT COUNT(C2) FROM TAB1 WHERE C1 IN ('b', 'c');

SELECT 500/0 FROM DUAL;

SELECT * FROM EMP_Q;

SELECT SAL / COMM FROM EMP_Q WHERE ENAME = 'KING';
SELECT SAL / COMM FROM EMP_Q WHERE ENAME = 'FORD';
SELECT SAL / COMM FROM EMP_Q WHERE ENAME = 'SCOTT';


--2014년 11월~ 2015년 3월 매출 합계
SELECT * FROM 월별매출;
UPDATE 월별매출 SET MON = '03' WHERE MON='3';

SELECT SUM(SALE) FROM 월별매출
WHERE YR BETWEEN '2014' AND '2015' AND MON BETWEEN '03' AND '12';

SELECT SUM(SALE) FROM 월별매출
WHERE YR IN ('2014', '2015') AND MON IN ('11', '12', '03', '04', '05');

SELECT SUM(SALE) FROM 월별매출
WHERE (YR = '2014' OR YR = '2015') AND (MON BETWEEN '01' AND '03' OR MON BETWEEN '11' AND '12');

SELECT SUM(SALE) FROM 월별매출
WHERE YR = '2014' AND MON BETWEEN '11' AND '12'
    OR YR = '2015' AND MON BETWEEN '01' AND '03';


SELECT * FROM TAB1_NULL;
SELECT SUM(COALESCE(C1, C2, C3)) FROM TAB1_NULL;

SELECT AVG(C3) FROM TEST34;
SELECT AVG(C3) FROM TEST34 WHERE C1 > 0;
SELECT AVG(C3) FROM TEST34 WHERE C1 IS NOT NULL;

SELECT GRAD, COUNT(*) FROM TEST35 GROUP BY GRAD;
SELECT COUNT(GRAD) FROM TEST35; 
SELECT COUNT(*) FROM TEST35; 