--5.4 TCL

--SET MANUAL COMMIT MODE BEFORE START THE DRILL

--5.4.7 COMMIT 
UPDATE TB_SUBWAY_STATN
	SET STATN_NM = '역삼역'
	WHERE STATN_NM = '역삼';
	
SELECT SUBWAY_STATN_NO,
		LN_NM,
		STATN_NM
FROM TB_SUBWAY_STATN
WHERE STATN_NM = '역삼역';

COMMIT;

UPDATE TB_SUBWAY_STATN
	SET STATN_NM = '역삼'
	WHERE STATN_NM = '역삼역';

--5.4.8 ROLLBACK
UPDATE TB_SUBWAY_STATN
	SET STATN_NM = '역삼역'
	WHERE STATN_NM = '역삼';

ROLLBACK;

SELECT SUBWAY_STATN_NO,
		LN_NM,
		STATN_NM
FROM TB_SUBWAY_STATN
WHERE STATN_NM LIKE '역삼%';

--5.4.9 SAVEPOINT

SELECT SUBWAY_STATN_NO,
		LN_NM,
		STATN_NM
FROM TB_SUBWAY_STATN
WHERE REGEXP_LIKE(STATN_NM, '강남.*|역삼.*|방배.*');

SAVEPOINT SVPT1;

UPDATE TB_SUBWAY_STATN
	SET STATN_NM = '역삼역'
	WHERE STATN_NM = '역삼';
	
SAVEPOINT SVPT2;

UPDATE TB_SUBWAY_STATN
	SET STATN_NM = '강남역'
	WHERE STATN_NM = '강남';
	
SAVEPOINT SVPT3;

UPDATE TB_SUBWAY_STATN
	SET STATN_NM = '방배역'
	WHERE STATN_NM = '방배';

SELECT SUBWAY_STATN_NO,
		LN_NM,
		STATN_NM
FROM TB_SUBWAY_STATN
WHERE REGEXP_LIKE(STATN_NM, '강남.*|역삼.*|방배.*');
	
ROLLBACK TO SVPT3;
ROLLBACK TO SVPT2;
ROLLBACK TO SVPT1;

--AUTOCOMMIT CASES:
-- - DML 다음에 DDL 실행했을 경우
-- - COMMIT 없이 종료하는 경우
--
--AUTOROLLBACK CASES:
--- 이상동작으로 인해 접속 단절