--5.5 WHERE

SELECT A.INDUTY_CL_CD ,
		A.INDUTY_CL_NM ,
		A.INDUTY_CL_SE_CD ,
		A.UPPER_INDUTY_CL_CD 
FROM TB_INDUTY_CL A
WHERE INDUTY_CL_NM LIKE '%커피%';

--강남역 2호선에서 2020년 10월 한달간 승차/하차 인원수 조회
--시작시간 오후 6시, 종료시간 오후 7시
SELECT
	A.SUBWAY_STATN_NO ,
	A.STD_YM ,
	A.BEGIN_TIME ,
	A.END_TIME ,
	A.TK_GFF_SE_CD ,
	A.TK_GFF_CNT
FROM
	TB_SUBWAY_STATN_TK_GFF A
WHERE
	A.SUBWAY_STATN_NO = '000032'
	-- 2호선 강남
	AND A.STD_YM = '202010'
	AND A.BEGIN_TIME LIKE '18%'
	AND A.END_TIME LIKE '19%'
	AND A.TK_GFF_SE_CD IN ('TGS001', 'TGS002');
	

-- IS NULL , IS NOT NULL

SELECT
	A.ADRES_CL_CD ,
	A.ADRES_CL_NM ,
	A.ADRES_CL_SE_CD ,
	NVL(A.UPPER_ADRES_CL_CD, '(Null)') AS UPPER_ADRES_CL_CD
FROM
	TB_ADRES_CL A
WHERE
	A.UPPER_ADRES_CL_CD IS NULL;

SELECT A.ADRES_CL_CD ,
		A.ADRES_CL_NM ,
		A.ADRES_CL_SE_CD ,
		NVL(A.UPPER_ADRES_CL_CD, '(Null)') AS UPPER_ADRES_CL_CD 
FROM TB_ADRES_CL A
WHERE A.UPPER_ADRES_CL_CD = NULL;

SELECT A.ADRES_CL_CD ,
		A.ADRES_CL_NM ,
		A.ADRES_CL_SE_CD ,
		NVL(A.UPPER_ADRES_CL_CD, '(Null)') AS UPPER_ADRES_CL_CD 
FROM TB_ADRES_CL A
WHERE A.UPPER_ADRES_CL_CD <> NULL;

SELECT A.ADRES_CL_CD ,
		A.ADRES_CL_NM ,
		A.ADRES_CL_SE_CD ,
		NVL(A.UPPER_ADRES_CL_CD, '(Null)') AS UPPER_ADRES_CL_CD 
FROM TB_ADRES_CL A
WHERE A.UPPER_ADRES_CL_CD IS NOT NULL;


-- LOGICAL OPERATOR AND/OR/NOT 

--서울특별시에 존재하는 커피전문점 중 스타벅스, 이디야, 파스쿠찌 매장을 찾는다.
--강남구 소재 매장은 제외한다.
SELECT A.BSSH_NO ,
		A.CMPNM_NM ,
		A.LNM_ADRES 
FROM TB_BSSH A
WHERE A.LNM_ADRES LIKE '서울%'
	AND
		(	A.CMPNM_NM LIKE '%스타벅스%'
		OR A.CMPNM_NM LIKE '%이디야%'
		OR A.CMPNM_NM LIKE '%파스쿠찌%'
		)
	AND NOT A.LNM_ADRES LIKE '%강남구%';
	
--NEGATION OPERATORS

SELECT A.SUBWAY_STATN_NO ,
		A.STD_YM ,
		A.BEGIN_TIME ,
		A.END_TIME ,
		CASE 
			WHEN A.TK_GFF_SE_CD = 'TGS001' THEN '승차'
			WHEN A.TK_GFF_SE_CD = 'TGS002' THEN '하차'
		END AS 승하차구분,
		A.TK_GFF_CNT	
FROM TB_SUBWAY_STATN_TK_GFF A
WHERE A.SUBWAY_STATN_NO = (SELECT SUBWAY_STATN_NO FROM TB_SUBWAY_STATN WHERE STATN_NM = '강남')
	AND A.STD_YM = '202010'
	AND A.TK_GFF_SE_CD IN ('TGS001', 'TGS002')
	AND NOT A.TK_GFF_CNT < 100000
ORDER BY A.TK_GFF_CNT DESC;

SELECT A.SUBWAY_STATN_NO ,
		A.STD_YM ,
		A.BEGIN_TIME ,
		A.END_TIME ,
		CASE 
			WHEN A.TK_GFF_SE_CD = 'TGS001' THEN '승차'
			WHEN A.TK_GFF_SE_CD = 'TGS002' THEN '하차'
		END AS 승하차구분,
		A.TK_GFF_CNT	
FROM TB_SUBWAY_STATN_TK_GFF A
WHERE A.SUBWAY_STATN_NO = (SELECT SUBWAY_STATN_NO FROM TB_SUBWAY_STATN WHERE STATN_NM = '강남')
	AND A.STD_YM = '202010'
	AND A.TK_GFF_SE_CD NOT IN ('TGS001')
	AND A.TK_GFF_CNT NOT BETWEEN 0 AND 99999
ORDER BY A.TK_GFF_CNT DESC;

--5.5.3 CHAR VS VARCHAR2

CREATE TABLE TB_CHAR
(
	CHAR_NO CHAR(4)
	, CHAR_4 CHAR(4)
	, CHAR_5 CHAR(5)
	, CONSTRAINT PK_TB_CHAR PRIMARY KEY (CHAR_NO)
);

INSERT INTO TB_CHAR (CHAR_NO, CHAR_4, CHAR_5)
	VALUES ('1001', 'SQLD', 'SQLD');
	
INSERT INTO TB_CHAR (CHAR_NO, CHAR_4, CHAR_5)
	VALUES ('1002', 'SQLD', 'SQLP');
	
COMMIT;

SELECT * FROM TB_CHAR;

SELECT
	  REPLACE(CHAR_4, ' ', '_') AS CHAR_4
	, REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR;

SELECT
	  REPLACE(CHAR_4, ' ', '_') AS CHAR_4
	, REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR
WHERE CHAR_4 = 'SQLD'
	AND CHAR_4 = CHAR_5;
	
	
SELECT
	  CHAR_NO
	, REPLACE(CHAR_4, ' ', '_') AS CHAR_4
	, REPLACE(CHAR_5, ' ', '_') AS CHAR_5
FROM TB_CHAR
WHERE CHAR_4 < CHAR_5;

-- 비교 연산자 중 한쪽이 VARCHAR2인 경우 

--테스트용 테이블 생성
CREATE TABLE TB_VARCHAR2
(
	VARCHAR_NO CHAR(4),
	CHAR_4 CHAR(4),
	VARCHAR2_5 VARCHAR2(5),
	CONSTRAINT PK_TB_VARCHAR2 PRIMARY KEY (VARCHAR_NO)	
);

--테스트용 데이터 입력
INSERT INTO TB_VARCHAR2 (VARCHAR_NO, CHAR_4, VARCHAR2_5)
	VALUES ('1001', 'SQLD', 'SQLD ');
	
INSERT INTO TB_VARCHAR2 (VARCHAR_NO, CHAR_4, VARCHAR2_5)
	VALUES ('1002', 'SQLD', 'SQLP ');
	
COMMIT;


SELECT
    REPLACE(CHAR_4, ' ', '_') AS CHAR_4,
    REPLACE(VARCHAR2_5, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2;   

SELECT
    REPLACE(CHAR_4, ' ', '_') AS CHAR_4,
    REPLACE(VARCHAR2_5, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
	AND CHAR_4 = VARCHAR2_5;
	
SELECT
    REPLACE(CHAR_4, ' ', '_') AS CHAR_4,
    REPLACE(VARCHAR2_5, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
	AND CHAR_4 = TRIM(VARCHAR2_5);

SELECT
    REPLACE(CHAR_4, ' ', '_') AS CHAR_4,
    REPLACE(VARCHAR2_5, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
	AND CHAR_4 = 'SQLD ';

SELECT
    REPLACE(CHAR_4, ' ', '_') AS CHAR_4,
    REPLACE(VARCHAR2_5, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2
WHERE VARCHAR_NO = '1001'
	AND VARCHAR2_5 = 'SQLD';


--5.5.4 ROWNUM ( LIMIT )

SELECT 
	ROWNUM AS RNUM,
	A.BSSH_NO,
	A.CMPNM_NM,
	NVL(A.BHF_NM, '(Null)') AS BHF_NM,
	A.LNM_ADRES
FROM
	TB_BSSH A
WHERE
	ROWNUM <= 10;