CREATE TABLE TB_VARCHAR2
(
	VARCHAR_NO CHAR(4),
	CHAR_4 CHAR(4),
	VARCHAR2_5 VARCHAR2(5),
	CONSTRAINT PK_TB_VARCHAR2 PRIMARY KEY (VARCHAR_NO)	
);

INSERT INTO TB_VARCHAR2 (VARCHAR_NO, CHAR_4, VARCHAR2_5)
	VALUES ('1001', 'SQLD', 'SQLD ');
	
INSERT INTO TB_VARCHAR2 (VARCHAR_NO, CHAR_4, VARCHAR2_5)
	VALUES ('1002', 'SQLD', 'SQLP ');
	
COMMIT;

SELECT
    REPLACE(CHAR_4, ' ', '_') AS CHAR_4,
    REPLACE(VARCHAR2_5, ' ', '_') AS VARCHAR2_5
FROM TB_VARCHAR2;    