CCREATE TABLE UTEST1 (
    AAA NUMBER,     ABB NUMBER
);

CREATE TABLE UTEST2 (
    BAA NUMBER,     BBB NUMBER
);

INSERT INTO UTEST1 VALUES (200, 50);

INSERT INTO UTEST2 VALUES (100, 230);


SELECT AAA AS AA, ABB AS AB FROM UTEST1
UNION ALL
SELECT BAA AS BA, BBB AS BA FROM UTEST2
ORDER BY 1, 2;

-- UNION ALL 에서 정렬 어떻게하든 먼저 쓴 칼럼네임 나옴
AA	AB
100	230
200	50



------------------------------------

CREATE TABLE TEST_TB1 (
    A NUMBER,
    B NUMBER
);

INSERT INTO TEST_TB1 VALUES (2, 4);
INSERT INTO TEST_TB1 VALUES (4, 6);

CREATE TABLE TMP_TEST_TB1 (
    A NUMBER,
    B NUMBER
);  -- COMMIT

INSERT INTO TEST_TB1 VALUES (2, 4);
INSERT INTO TEST_TB1 VALUES (4, 6);

TRUNCATE TABLE TMP_TEST_TB1;  -- COMMIT

ROLLBACK;

SELECT SUM(A), SUM(B) FROM TEST_TB1;

SUM(A)	SUM(B)
12	20

NO TRUNCATE -> 6	10

----------------------------------------

CREATE TABLE ERRTEST (
    "ID" CHAR(3) PRIMARY KEY,
    "DATE" DATE,
    "NAME" CHAR(10) NOT NULL,
    "CODE" CHAR(3) DEFAULT '000'
);

INSERT INTO  ERRTEST
VALUES(1, SYSDATE, 'AAA', 120);
-- IMPLICITLY CONVERT NUM -> CHAR

INSERT INTO  ERRTEST
VALUES(2, SYSDATE-1, 'BBB', '130');

INSERT INTO  ERRTEST
VALUES(3, '20190801', 'CCC', '130'); 
-- ORA-01861: literal does not match format string ORA-06512

INSERT INTO  ERRTEST
VALUES(4, TO_CHAR(SYSDATE, 'YYYY-MM-DD'), 'DDD', '130'); 
-- ORA-01861: literal does not match format string ORA-06512

INSERT INTO  ERRTEST
VALUES(5, 20320612, 'EEE', '130'); 
-- ORA-00932: inconsistent datatypes: expected DATE got NUMBER 

INSERT INTO  ERRTEST
VALUES(6, TO_DATE('2020-04-13', 'YYYY-MM-DD'), 'FFF', '140');

SELECT * FROM ERRTEST;

/*
ID	DATE	NAME	CODE
1  	12-MAR-22	AAA       	120
2  	11-MAR-22	BBB       	130
4  	13-APR-20	DDD       	140
*/

-------------------------------------------
주관식 3번 틀림
ROW_ID   ->   ROW_NUMBER